language: r
cache: packages
warnings_are_errors: false
r:
  - release
before_install:
  - tlmgr install index
  - sudo apt-get -y install  libglu1-mesa-dev
before_cache: Rscript -e 'remotes::install_cran("pkgdown")'
r_packages:
  - covr
  - lintr
env:
  - ON_TRAVIS = 1
after_success:
  - R CMD INSTALL $PKG_TARBALL
  - Rscript -e 'library(covr); codecov()'
  - Rscript -e 'lintr::lint_package()'
  - Rscript -e 'pkgdown::build_site()'
deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github(ssh_id = Sys.getenv("TRAVIS_DEPLOY_KEY", ""))'
  skip_cleanup: true
